-- MySQL Script generated by MySQL Workbench
-- Qui 17 Nov 2016 09:38:54 BRST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`USUARIO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`USUARIO` (
  `Usuario_ID` INT UNSIGNED NOT NULL,
  `Nome_Usuario` VARCHAR(45) NOT NULL,
  `DataNasc` DATE NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Sexo` CHAR(1) NOT NULL,
  `Peso` DECIMAL NOT NULL,
  `Altura` DECIMAL NULL,
  PRIMARY KEY (`Usuario_ID`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Uid_UNIQUE` ON `mydb`.`USUARIO` (`Usuario_ID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`dieta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`dieta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`dieta` (
  `Did` INT UNSIGNED NOT NULL,
  `Aid` INT NULL,
  `qtde_porção` SMALLINT NOT NULL,
  `usuário_Uid` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Did`, `usuário_Uid`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Did_UNIQUE` ON `mydb`.`dieta` (`Did` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`refeição`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`refeição` ;

CREATE TABLE IF NOT EXISTS `mydb`.`refeição` (
  `Rid` INT NOT NULL,
  `Data` DATE NOT NULL,
  `Hora` TIME NOT NULL,
  `dieta_Did` INT UNSIGNED NOT NULL,
  `dieta_usuário_Uid` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Rid`, `dieta_Did`, `dieta_usuário_Uid`),
  CONSTRAINT `fk_refeição_dieta1`
    FOREIGN KEY (`dieta_Did` , `dieta_usuário_Uid`)
    REFERENCES `mydb`.`dieta` (`Did` , `usuário_Uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Rid_UNIQUE` ON `mydb`.`refeição` (`Rid` ASC);

CREATE INDEX `fk_refeição_dieta1_idx` ON `mydb`.`refeição` (`dieta_Did` ASC, `dieta_usuário_Uid` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`grupo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`grupo` (
  `Gid` INT UNSIGNED NOT NULL,
  `GNome` VARCHAR(45) NOT NULL,
  `nutriente_principal` VARCHAR(45) NOT NULL,
  `qtde_diaria_recomendada` SMALLINT NOT NULL,
  PRIMARY KEY (`Gid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sub_grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sub_grupo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sub_grupo` (
  `GSid` INT NOT NULL,
  `GSNome` VARCHAR(45) NOT NULL,
  `grupo_Gid` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`GSid`, `grupo_Gid`),
  CONSTRAINT `fk_sub_grupo_grupo1`
    FOREIGN KEY (`grupo_Gid`)
    REFERENCES `mydb`.`grupo` (`Gid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `GSid_UNIQUE` ON `mydb`.`sub_grupo` (`GSid` ASC);

CREATE INDEX `fk_sub_grupo_grupo1_idx` ON `mydb`.`sub_grupo` (`grupo_Gid` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`alimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`alimento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`alimento` (
  `Alimento_ID` INT NOT NULL,
  `ANome` VARCHAR(45) NOT NULL,
  `Descrição` VARCHAR(45) NOT NULL,
  `sub_grupo_GSid` INT NOT NULL,
  `sub_grupo_grupo_Gid` INT UNSIGNED NOT NULL,
  `dieta_Did` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Alimento_ID`, `sub_grupo_GSid`, `sub_grupo_grupo_Gid`, `dieta_Did`),
  CONSTRAINT `fk_alimento_sub_grupo1`
    FOREIGN KEY (`sub_grupo_GSid` , `sub_grupo_grupo_Gid`)
    REFERENCES `mydb`.`sub_grupo` (`GSid` , `grupo_Gid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Aid_UNIQUE` ON `mydb`.`alimento` (`Alimento_ID` ASC);

CREATE INDEX `fk_alimento_sub_grupo1_idx` ON `mydb`.`alimento` (`sub_grupo_GSid` ASC, `sub_grupo_grupo_Gid` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`energético`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`energético` ;

CREATE TABLE IF NOT EXISTS `mydb`.`energético` (
  `qtde_carboidrato` DECIMAL NOT NULL,
  `alimento_Aid` INT NOT NULL,
  `alimento_sub_grupo_GSid` INT NOT NULL,
  `alimento_sub_grupo_grupo_Gid` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`alimento_Aid`, `alimento_sub_grupo_GSid`, `alimento_sub_grupo_grupo_Gid`),
  CONSTRAINT `fk_energético_alimento1`
    FOREIGN KEY (`alimento_Aid` , `alimento_sub_grupo_GSid` , `alimento_sub_grupo_grupo_Gid`)
    REFERENCES `mydb`.`alimento` (`Alimento_ID` , `sub_grupo_GSid` , `sub_grupo_grupo_Gid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`regulador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`regulador` ;

CREATE TABLE IF NOT EXISTS `mydb`.`regulador` (
  `qtde_fibra` DECIMAL NOT NULL,
  `alimento_Aid` INT NOT NULL,
  `alimento_sub_grupo_GSid` INT NOT NULL,
  `alimento_sub_grupo_grupo_Gid` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`alimento_Aid`, `alimento_sub_grupo_GSid`, `alimento_sub_grupo_grupo_Gid`),
  CONSTRAINT `fk_regulador_alimento1`
    FOREIGN KEY (`alimento_Aid` , `alimento_sub_grupo_GSid` , `alimento_sub_grupo_grupo_Gid`)
    REFERENCES `mydb`.`alimento` (`Alimento_ID` , `sub_grupo_GSid` , `sub_grupo_grupo_Gid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`construtor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`construtor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`construtor` (
  `qtde_proteina` DECIMAL NOT NULL,
  `alimento_Aid` INT NOT NULL,
  `alimento_sub_grupo_GSid` INT NOT NULL,
  `alimento_sub_grupo_grupo_Gid` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`alimento_Aid`, `alimento_sub_grupo_GSid`, `alimento_sub_grupo_grupo_Gid`),
  CONSTRAINT `fk_construtor_alimento1`
    FOREIGN KEY (`alimento_Aid` , `alimento_sub_grupo_GSid` , `alimento_sub_grupo_grupo_Gid`)
    REFERENCES `mydb`.`alimento` (`Alimento_ID` , `sub_grupo_GSid` , `sub_grupo_grupo_Gid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`energetico_extra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`energetico_extra` ;

CREATE TABLE IF NOT EXISTS `mydb`.`energetico_extra` (
  `qtde_permitida` SMALLINT NOT NULL,
  `alimento_Aid` INT NOT NULL,
  `alimento_sub_grupo_GSid` INT NOT NULL,
  `alimento_sub_grupo_grupo_Gid` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`alimento_Aid`, `alimento_sub_grupo_GSid`, `alimento_sub_grupo_grupo_Gid`),
  CONSTRAINT `fk_energetico_extra_alimento1`
    FOREIGN KEY (`alimento_Aid` , `alimento_sub_grupo_GSid` , `alimento_sub_grupo_grupo_Gid`)
    REFERENCES `mydb`.`alimento` (`Alimento_ID` , `sub_grupo_GSid` , `sub_grupo_grupo_Gid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ALIMENTO_USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ALIMENTO_USUARIO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ALIMENTO_USUARIO` (
  `alimento_Alimento_ID` INT NOT NULL,
  `alimento_sub_grupo_GSid` INT NOT NULL,
  `alimento_sub_grupo_grupo_Gid` INT UNSIGNED NOT NULL,
  `alimento_dieta_Did` INT UNSIGNED NOT NULL,
  `usuário_Usuario_ID` INT UNSIGNED NOT NULL,
  `dieta_Did` INT UNSIGNED NOT NULL,
  `dieta_usuário_Uid` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`alimento_Alimento_ID`, `alimento_sub_grupo_GSid`, `alimento_sub_grupo_grupo_Gid`, `alimento_dieta_Did`, `usuário_Usuario_ID`, `dieta_Did`, `dieta_usuário_Uid`),
  CONSTRAINT `fk_alimento_has_usuário_alimento1`
    FOREIGN KEY (`alimento_Alimento_ID` , `alimento_sub_grupo_GSid` , `alimento_sub_grupo_grupo_Gid` , `alimento_dieta_Did`)
    REFERENCES `mydb`.`alimento` (`Alimento_ID` , `sub_grupo_GSid` , `sub_grupo_grupo_Gid` , `dieta_Did`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alimento_has_usuário_usuário1`
    FOREIGN KEY (`usuário_Usuario_ID`)
    REFERENCES `mydb`.`USUARIO` (`Usuario_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ALIMENTO_USUARIO_dieta1`
    FOREIGN KEY (`dieta_Did` , `dieta_usuário_Uid`)
    REFERENCES `mydb`.`dieta` (`Did` , `usuário_Uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_alimento_has_usuário_usuário1_idx` ON `mydb`.`ALIMENTO_USUARIO` (`usuário_Usuario_ID` ASC);

CREATE INDEX `fk_alimento_has_usuário_alimento1_idx` ON `mydb`.`ALIMENTO_USUARIO` (`alimento_Alimento_ID` ASC, `alimento_sub_grupo_GSid` ASC, `alimento_sub_grupo_grupo_Gid` ASC, `alimento_dieta_Did` ASC);

CREATE INDEX `fk_ALIMENTO_USUARIO_dieta1_idx` ON `mydb`.`ALIMENTO_USUARIO` (`dieta_Did` ASC, `dieta_usuário_Uid` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
